name: Build and test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .